import * as Assets_1 from "./assets.js";
export { Assets_1 as Assets };
export var WeaponCategory;
(function (WeaponCategory) {
    WeaponCategory[WeaponCategory["BOW"] = 0] = "BOW";
    WeaponCategory[WeaponCategory["CATALYST"] = 1] = "CATALYST";
    WeaponCategory[WeaponCategory["CLAYMORE"] = 2] = "CLAYMORE";
    WeaponCategory[WeaponCategory["POLEARM"] = 3] = "POLEARM";
    WeaponCategory[WeaponCategory["SWORD"] = 4] = "SWORD";
})(WeaponCategory || (WeaponCategory = {}));
// characters
export const characters = [
    {
        id: "Albedo",
        type: "character",
        rarity: 5,
        name: { en: ["Albedo"], "zh-CN": ["阿贝多"] },
        materials: ["Prithiva Topaz", "Basalt Pillar", "Tusk of Monoceros Caeli", "Ballad", "Divining Scroll", "Cecilia"],
    },
    {
        id: "Aloy",
        type: "character",
        rarity: 5,
        name: { en: ["Aloy"], "zh-CN": ["埃洛伊"] },
        materials: ["Shivada Jade", "Crystalline Bloom", "Molten Moment", "Freedom", "Spectral Husk", "Crystal Marrow"],
    },
    {
        id: "Amber",
        type: "character",
        rarity: 4,
        name: { en: ["Amber"], "zh-CN": ["安柏"] },
        materials: ["Agnidus Agate", "Everflame Seed", "Dvalin’s Sigh", "Freedom", "Firm Arrowhead", "Small Lamp Grass"],
    },
    {
        id: "Arataki Itto",
        type: "character",
        rarity: 5,
        name: { en: ["Arataki Itto"], "zh-CN": ["荒泷一斗"] },
        materials: ["Prithiva Topaz", "Riftborn Regalia", "Ashen Heart", "Elegance", "Slime Condensate", "Onikabuto"],
    },
    {
        id: "Barbara",
        type: "character",
        rarity: 4,
        name: { en: ["Barbara"], "zh-CN": ["芭芭拉"] },
        materials: [
            "Varunada Lazurite",
            "Cleansing Heart",
            "Ring of Boreas",
            "Freedom",
            "Divining Scroll",
            "Philanemo Mushroom",
        ],
    },
    {
        id: "Beidou",
        type: "character",
        rarity: 4,
        name: { en: ["Beidou"], "zh-CN": ["北斗"] },
        materials: [
            "Vajrada Amethyst",
            "Lightning Prism",
            "Dvalin’s Sigh",
            "Gold",
            "Treasure Hoarder Insignia",
            "Noctilucous Jade",
        ],
    },
    {
        id: "Bennett",
        type: "character",
        rarity: 4,
        name: { en: ["Bennett"], "zh-CN": ["班尼特"] },
        materials: [
            "Agnidus Agate",
            "Everflame Seed",
            "Dvalin’s Plume",
            "Resistance",
            "Treasure Hoarder Insignia",
            "Windwheel Aster",
        ],
    },
    {
        id: "Chongyun",
        type: "character",
        rarity: 4,
        name: { en: ["Chongyun"], "zh-CN": ["重云"] },
        materials: ["Shivada Jade", "Hoarfrost Core", "Dvalin’s Sigh", "Diligence", "Damaged Mask", "Cor Lapis"],
    },
    {
        id: "Diluc",
        type: "character",
        rarity: 5,
        name: { en: ["Diluc"], "zh-CN": ["迪卢克"] },
        materials: [
            "Agnidus Agate",
            "Everflame Seed",
            "Dvalin’s Plume",
            "Resistance",
            "Recruit’s Insignia",
            "Small Lamp Grass",
        ],
    },
    {
        id: "Diona",
        type: "character",
        rarity: 4,
        name: { en: ["Diona"], "zh-CN": ["迪奥娜"] },
        materials: ["Shivada Jade", "Hoarfrost Core", "Shard of a Foul Legacy", "Freedom", "Firm Arrowhead", "Calla Lily"],
    },
    {
        id: "Eula",
        type: "character",
        rarity: 5,
        name: { en: ["Eula"], "zh-CN": ["优菈"] },
        materials: [
            "Shivada Jade",
            "Crystalline Bloom",
            "Dragon Lord’s Crown",
            "Resistance",
            "Damaged Mask",
            "Dandelion Seed",
        ],
    },
    {
        id: "Fischl",
        type: "character",
        rarity: 4,
        name: { en: ["Fischl"], "zh-CN": ["菲谢尔"] },
        materials: [
            "Vajrada Amethyst",
            "Lightning Prism",
            "Spirit Locket of Boreas",
            "Ballad",
            "Firm Arrowhead",
            "Small Lamp Grass",
        ],
    },
    {
        id: "Ganyu",
        type: "character",
        rarity: 5,
        name: { en: ["Ganyu"], "zh-CN": ["甘雨"] },
        materials: [
            "Shivada Jade",
            "Hoarfrost Core",
            "Shadow of the Warrior",
            "Diligence",
            "Whopperflower Nectar",
            "Qingxin",
        ],
    },
    {
        id: "Gorou",
        type: "character",
        rarity: 4,
        name: { en: ["Gorou"], "zh-CN": ["五郎"] },
        materials: ["Prithiva Topaz", "Perpetual Heart", "Molten Moment", "Light", "Spectral Husk", "Sango Pearl"],
    },
    {
        id: "Hu Tao",
        type: "character",
        rarity: 5,
        name: { en: ["Hu Tao"], "zh-CN": ["胡桃"] },
        materials: [
            "Agnidus Agate",
            "Juvenile Jade",
            "Shard of a Foul Legacy",
            "Diligence",
            "Whopperflower Nectar",
            "Silk Flower",
        ],
    },
    {
        id: "Jean",
        type: "character",
        rarity: 5,
        name: { en: ["Jean"], "zh-CN": ["琴"] },
        materials: ["Vayuda Turquoise", "Hurricane Seed", "Dvalin’s Plume", "Resistance", "Damaged Mask", "Dandelion Seed"],
    },
    {
        id: "Kaedehara Kazuha",
        type: "character",
        rarity: 5,
        name: { en: ["Kaedehara Kazuha"], "zh-CN": ["枫原万叶"] },
        materials: [
            "Vayuda Turquoise",
            "Marionette Core",
            "Gilded Scale",
            "Diligence",
            "Treasure Hoarder Insignia",
            "Sea Ganoderma",
        ],
    },
    {
        id: "Kaeya",
        type: "character",
        rarity: 4,
        name: { en: ["Kaeya"], "zh-CN": ["凯亚"] },
        materials: [
            "Shivada Jade",
            "Hoarfrost Core",
            "Spirit Locket of Boreas",
            "Ballad",
            "Treasure Hoarder Insignia",
            "Calla Lily",
        ],
    },
    {
        id: "Kamisato Ayaka",
        type: "character",
        rarity: 5,
        name: { en: ["Kamisato Ayaka"], "zh-CN": ["神里绫华"] },
        materials: ["Shivada Jade", "Perpetual Heart", "Bloodjade Branch", "Elegance", "Old Handguard", "Sakura Bloom"],
    },
    {
        id: "Keqing",
        type: "character",
        rarity: 5,
        name: { en: ["Keqing"], "zh-CN": ["刻晴"] },
        materials: [
            "Vajrada Amethyst",
            "Lightning Prism",
            "Ring of Boreas",
            "Prosperity",
            "Whopperflower Nectar",
            "Cor Lapis",
        ],
    },
    {
        id: "Klee",
        type: "character",
        rarity: 5,
        name: { en: ["Klee"], "zh-CN": ["可莉"] },
        materials: [
            "Agnidus Agate",
            "Everflame Seed",
            "Ring of Boreas",
            "Freedom",
            "Divining Scroll",
            "Philanemo Mushroom",
        ],
    },
    {
        id: "Kujou Sara",
        type: "character",
        rarity: 4,
        name: { en: ["Kujou Sara"], "zh-CN": ["九条裟罗"] },
        materials: ["Vajrada Amethyst", "Storm Beads", "Ashen Heart", "Elegance", "Damaged Mask", "Dendrobium"],
    },
    {
        id: "Lisa",
        type: "character",
        rarity: 4,
        name: { en: ["Lisa"], "zh-CN": ["丽莎"] },
        materials: ["Vajrada Amethyst", "Lightning Prism", "Dvalin’s Claw", "Ballad", "Slime Condensate", "Valberry"],
    },
    {
        id: "Mona",
        type: "character",
        rarity: 5,
        name: { en: ["Mona"], "zh-CN": ["莫娜"] },
        materials: [
            "Varunada Lazurite",
            "Cleansing Heart",
            "Ring of Boreas",
            "Resistance",
            "Whopperflower Nectar",
            "Philanemo Mushroom",
        ],
    },
    {
        id: "Ningguang",
        type: "character",
        rarity: 4,
        name: { en: ["Ningguang"], "zh-CN": ["凝光"] },
        materials: [
            "Prithiva Topaz",
            "Basalt Pillar",
            "Spirit Locket of Boreas",
            "Prosperity",
            "Recruit’s Insignia",
            "Glaze Lily",
        ],
    },
    {
        id: "Noelle",
        type: "character",
        rarity: 4,
        name: { en: ["Noelle"], "zh-CN": ["诺艾尔"] },
        materials: ["Prithiva Topaz", "Basalt Pillar", "Dvalin’s Claw", "Resistance", "Damaged Mask", "Valberry"],
    },
    {
        id: "Qiqi",
        type: "character",
        rarity: 5,
        name: { en: ["Qiqi"], "zh-CN": ["七七"] },
        materials: ["Shivada Jade", "Hoarfrost Core", "Tail of Boreas", "Prosperity", "Divining Scroll", "Violetgrass"],
    },
    {
        id: "Raiden Shogun",
        type: "character",
        rarity: 5,
        name: { en: ["Raiden Shogun"], "zh-CN": ["雷电将军"] },
        materials: ["Vajrada Amethyst", "Storm Beads", "Molten Moment", "Light", "Old Handguard", "Amakumo Fruit"],
    },
    {
        id: "Razor",
        type: "character",
        rarity: 4,
        name: { en: ["Razor"], "zh-CN": ["雷泽"] },
        materials: ["Vajrada Amethyst", "Lightning Prism", "Dvalin’s Claw", "Resistance", "Damaged Mask", "Wolfhook"],
    },
    {
        id: "Rosaria",
        type: "character",
        rarity: 4,
        name: { en: ["Rosaria"], "zh-CN": ["罗莎莉亚"] },
        materials: ["Shivada Jade", "Hoarfrost Core", "Shadow of the Warrior", "Ballad", "Recruit’s Insignia", "Valberry"],
    },
    {
        id: "Sangonomiya Kokomi",
        type: "character",
        rarity: 5,
        name: { en: ["Sangonomiya Kokomi"], "zh-CN": ["珊瑚宫心海"] },
        materials: [
            "Varunada Lazurite",
            "Dew of Repudiation",
            "Hellfire Butterfly",
            "Transience",
            "Spectral Husk",
            "Sango Pearl",
        ],
    },
    {
        id: "Sayu",
        type: "character",
        rarity: 4,
        name: { en: ["Sayu"], "zh-CN": ["早柚"] },
        materials: [
            "Vayuda Turquoise",
            "Marionette Core",
            "Gilded Scale",
            "Light",
            "Whopperflower Nectar",
            "Crystal Marrow",
        ],
    },
    {
        id: "Shenhe",
        type: "character",
        rarity: 5,
        name: { en: ["Shenhe"], "zh-CN": ["申鹤"] },
        materials: [
            "Shivada Jade",
            "Dragonheir’s False Fin",
            "Hellfire Butterfly",
            "Prosperity",
            "Whopperflower Nectar",
            "Qingxin",
        ],
    },
    {
        id: "Sucrose",
        type: "character",
        rarity: 4,
        name: { en: ["Sucrose"], "zh-CN": ["砂糖"] },
        materials: [
            "Vayuda Turquoise",
            "Hurricane Seed",
            "Spirit Locket of Boreas",
            "Freedom",
            "Whopperflower Nectar",
            "Windwheel Aster",
        ],
    },
    {
        id: "Tartaglia",
        type: "character",
        rarity: 5,
        name: { en: ["Tartaglia"], "zh-CN": ["达达利亚"] },
        materials: [
            "Varunada Lazurite",
            "Cleansing Heart",
            "Shard of a Foul Legacy",
            "Freedom",
            "Recruit’s Insignia",
            "Starconch",
        ],
    },
    {
        id: "Thoma",
        type: "character",
        rarity: 4,
        name: { en: ["Thoma"], "zh-CN": ["托马"] },
        materials: [
            "Agnidus Agate",
            "Smoldering Pearl",
            "Hellfire Butterfly",
            "Transience",
            "Treasure Hoarder Insignia",
            "Fluorescent Fungus",
        ],
    },
    {
        id: "Venti",
        type: "character",
        rarity: 5,
        name: { en: ["Venti"], "zh-CN": ["温迪"] },
        materials: ["Vayuda Turquoise", "Hurricane Seed", "Tail of Boreas", "Ballad", "Slime Condensate", "Cecilia"],
    },
    {
        id: "Xiangling",
        type: "character",
        rarity: 4,
        name: { en: ["Xiangling"], "zh-CN": ["香菱"] },
        materials: ["Agnidus Agate", "Everflame Seed", "Dvalin’s Claw", "Diligence", "Slime Condensate", "Jueyun Chili"],
    },
    {
        id: "Xiao",
        type: "character",
        rarity: 5,
        name: { en: ["Xiao"], "zh-CN": ["魈"] },
        materials: [
            "Vayuda Turquoise",
            "Juvenile Jade",
            "Shadow of the Warrior",
            "Prosperity",
            "Slime Condensate",
            "Qingxin",
        ],
    },
    {
        id: "Xingqiu",
        type: "character",
        rarity: 4,
        name: { en: ["Xingqiu"], "zh-CN": ["行秋"] },
        materials: ["Varunada Lazurite", "Cleansing Heart", "Tail of Boreas", "Gold", "Damaged Mask", "Silk Flower"],
    },
    {
        id: "Xinyan",
        type: "character",
        rarity: 4,
        name: { en: ["Xinyan"], "zh-CN": ["辛焱"] },
        materials: [
            "Agnidus Agate",
            "Everflame Seed",
            "Tusk of Monoceros Caeli",
            "Gold",
            "Treasure Hoarder Insignia",
            "Violetgrass",
        ],
    },
    {
        id: "Yae Miko",
        type: "character",
        rarity: 5,
        name: {
            en: ["Yae Miko"],
            "zh-CN": ["八重神子"],
        },
        materials: ["Vajrada Amethyst", "Dragonheir’s False Fin", "Light", "Old Handguard", "Sea Ganoderma"],
    },
    {
        id: "Yanfei",
        type: "character",
        rarity: 4,
        name: { en: ["Yanfei"], "zh-CN": ["烟绯"] },
        materials: [
            "Agnidus Agate",
            "Juvenile Jade",
            "Bloodjade Branch",
            "Gold",
            "Treasure Hoarder Insignia",
            "Noctilucous Jade",
        ],
    },
    {
        id: "Yoimiya",
        type: "character",
        rarity: 5,
        name: { en: ["Yoimiya"], "zh-CN": ["宵宫"] },
        materials: [
            "Agnidus Agate",
            "Smoldering Pearl",
            "Dragon Lord’s Crown",
            "Transience",
            "Divining Scroll",
            "Naku Weed",
        ],
    },
    {
        id: "Yun Jin",
        type: "character",
        rarity: 4,
        name: { en: ["Yun Jin"], "zh-CN": ["云堇"] },
        materials: ["Prithiva Topaz", "Riftborn Regalia", "Ashen Heart", "Diligence", "Damaged Mask", "Glaze Lily"],
    },
    {
        id: "Zhongli",
        type: "character",
        rarity: 5,
        name: { en: ["Zhongli"], "zh-CN": ["钟离"] },
        materials: ["Prithiva Topaz", "Basalt Pillar", "Tusk of Monoceros Caeli", "Gold", "Slime Condensate", "Cor Lapis"],
    },
];
// weapons
export const weapons = [
    {
        id: "Polar Star",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.BOW,
        name: { en: ["Polar Star"], "zh-CN": ["冬极白星"] },
        materials: ["Mask of the Wicked Lieutenant", "Concealed Claw", "Spectral Husk"],
    },
    {
        id: "Thundering Pulse",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.BOW,
        name: { en: ["Thundering Pulse"], "zh-CN": ["飞雷之弦振"] },
        materials: ["Narukami’s Wisdom", "Dismal Prism", "Firm Arrowhead"],
    },
    {
        id: "Elegy for the End",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.BOW,
        name: { en: ["Elegy for the End"], "zh-CN": ["终末嗟叹之诗"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Heavy Horn", "Recruit’s Insignia"],
    },
    {
        id: "Skyward Harp",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.BOW,
        name: { en: ["Skyward Harp"], "zh-CN": ["天空之翼"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Firm Arrowhead"],
    },
    {
        id: "Amos’ Bow",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.BOW,
        name: { en: ["Amos’ Bow"], "zh-CN": ["阿莫斯之弓"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Slime Condensate"],
    },
    {
        id: "Alley Hunter",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Alley Hunter"], "zh-CN": ["暗巷猎手"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Slime Condensate"],
    },
    {
        id: "The Viridescent Hunt",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["The Viridescent Hunt"], "zh-CN": ["苍翠猎弓"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Firm Arrowhead"],
    },
    {
        id: "The Stringless",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["The Stringless"], "zh-CN": ["绝弦"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Firm Arrowhead"],
    },
    {
        id: "Sacrificial Bow",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Sacrificial Bow"], "zh-CN": ["祭礼弓"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Slime Condensate"],
    },
    {
        id: "Rust",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Rust"], "zh-CN": ["弓藏"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Damaged Mask"],
    },
    {
        id: "Royal Bow",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Royal Bow"], "zh-CN": ["宗室长弓"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Divining Scroll"],
    },
    {
        id: "Predator",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Predator"], "zh-CN": ["掠食者"] },
        materials: ["Narukami’s Wisdom", "Dismal Prism", "Firm Arrowhead"],
    },
    {
        id: "Prototype Crescent",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Prototype Crescent"], "zh-CN": ["试作澹月"] },
        materials: [
            "Northlander Bow Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Mist Veiled Lead Elixir",
            "Mist Grass Pollen",
            "Treasure Hoarder Insignia",
        ],
    },
    {
        id: "Mouun’s Moon",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Mouun’s Moon"], "zh-CN": ["曚云之月"] },
        materials: ["Narukami’s Wisdom", "Dismal Prism", "Spectral Husk"],
    },
    {
        id: "Mitternachts Waltz",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Mitternachts Waltz"], "zh-CN": ["幽夜华尔兹"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Treasure Hoarder Insignia"],
    },
    {
        id: "Hamayumi",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Hamayumi"], "zh-CN": ["破魔之弓"] },
        materials: [
            "Northlander Bow Billet",
            "Amethyst Lump",
            "White Iron Chunk",
            "Narukami’s Wisdom",
            "Dismal Prism",
            "Firm Arrowhead",
        ],
    },
    {
        id: "Favonius Warbow",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Favonius Warbow"], "zh-CN": ["西风猎弓"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Whopperflower Nectar"],
    },
    {
        id: "Compound Bow",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Compound Bow"], "zh-CN": ["钢轮弓"] },
        materials: [
            "Northlander Bow Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Grain of Aerosiderite",
            "Fragile Bone Shard",
            "Recruit’s Insignia",
        ],
    },
    {
        id: "Blackcliff Warbow",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Blackcliff Warbow"], "zh-CN": ["黑岩战弓"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Whopperflower Nectar"],
    },
    {
        id: "Windblume Ode",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.BOW,
        name: { en: ["Windblume Ode"], "zh-CN": ["风花之颂"] },
        materials: ["Fetters of the Dandelion Gladiator", "Dead Ley Line Branch", "Whopperflower Nectar"],
    },
    {
        id: "Raven Bow",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.BOW,
        name: { en: ["Raven Bow"], "zh-CN": ["鸦羽弓"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Firm Arrowhead"],
    },
    {
        id: "Recurve Bow",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.BOW,
        name: { en: ["Recurve Bow"], "zh-CN": ["反曲弓"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Divining Scroll"],
    },
    {
        id: "Messenger",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.BOW,
        name: { en: ["Messenger"], "zh-CN": ["信使"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Treasure Hoarder Insignia"],
    },
    {
        id: "Sharpshooter’s Oath",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.BOW,
        name: { en: ["Sharpshooter’s Oath"], "zh-CN": ["神射手之誓"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Slime Condensate"],
    },
    {
        id: "Slingshot",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.BOW,
        name: { en: ["Slingshot"], "zh-CN": ["弹弓"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Damaged Mask"],
    },
    {
        id: "Lost Prayer to the Sacred Winds",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CATALYST,
        name: { en: ["Lost Prayer to the Sacred Winds"], "zh-CN": ["四风原典"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Slime Condensate"],
    },
    {
        id: "Skyward Atlas",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CATALYST,
        name: { en: ["Skyward Atlas"], "zh-CN": ["天空之卷"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Firm Arrowhead"],
    },
    {
        id: "Everlasting Moonglow",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CATALYST,
        name: { en: ["Everlasting Moonglow"], "zh-CN": ["不灭月华"] },
        materials: ["Coral Branch of a Distant Sea", "Dismal Prism", "Spectral Husk"],
    },
    {
        id: "Memory of Dust",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CATALYST,
        name: { en: ["Memory of Dust"], "zh-CN": ["尘世之锁"] },
        materials: ["Grain of Aerosiderite", "Fragile Bone Shard", "Damaged Mask"],
    },
    {
        id: "Kagura’s Verity",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CATALYST,
        name: { en: ["Kagura’s Verity"], "zh-CN": ["神乐之真意"] },
        materials: ["Mask of the Wicked Lieutenant", "Concealed Claw", "Spectral Husk"],
    },
    {
        id: "Wine and Song",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Wine and Song"], "zh-CN": ["暗巷的酒与诗"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Treasure Hoarder Insignia"],
    },
    {
        id: "The Widsith",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["The Widsith"], "zh-CN": ["流浪乐章"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Damaged Mask"],
    },
    {
        id: "Solar Pearl",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Solar Pearl"], "zh-CN": ["匣里日月"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Whopperflower Nectar"],
    },
    {
        id: "Sacrificial Fragments",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Sacrificial Fragments"], "zh-CN": ["祭礼残章"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Treasure Hoarder Insignia"],
    },
    {
        id: "Royal Grimoire",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Royal Grimoire"], "zh-CN": ["宗室秘法录"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Recruit’s Insignia"],
    },
    {
        id: "Prototype Amber",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Prototype Amber"], "zh-CN": ["试作金珀"] },
        materials: [
            "Northlander Catalyst Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Mist Veiled Lead Elixir",
            "Mist Grass Pollen",
            "Firm Arrowhead",
        ],
    },
    {
        id: "Mappa Mare",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Mappa Mare"], "zh-CN": ["万国诸海图谱"] },
        materials: [
            "Northlander Catalyst Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Grain of Aerosiderite",
            "Fragile Bone Shard",
            "Slime Condensate",
        ],
    },
    {
        id: "Hakushin Ring",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Hakushin Ring"], "zh-CN": ["白辰之环"] },
        materials: [
            "Northlander Catalyst Billet",
            "Amethyst Lump",
            "White Iron Chunk",
            "Coral Branch of a Distant Sea",
            "Dismal Prism",
            "Divining Scroll",
        ],
    },
    {
        id: "Frostbearer",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Frostbearer"], "zh-CN": ["忍冬之果"] },
        materials: [
            "Northlander Catalyst Billet",
            "Crystal Chunk",
            "Starsilver",
            "Fetters of the Dandelion Gladiator",
            "Chaos Device",
            "Whopperflower Nectar",
        ],
    },
    {
        id: "Favonius Codex",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Favonius Codex"], "zh-CN": ["西风秘典"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Divining Scroll"],
    },
    {
        id: "Eye of Perception",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Eye of Perception"], "zh-CN": ["昭心"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Damaged Mask"],
    },
    {
        id: "Dodoco Tales",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Dodoco Tales"], "zh-CN": ["嘟嘟可故事集"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Damaged Mask"],
    },
    {
        id: "Blackcliff Agate",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Blackcliff Agate"], "zh-CN": ["黑岩绯玉"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Divining Scroll"],
    },
    {
        id: "Oathsworn Eye",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CATALYST,
        name: { en: ["Oathsworn Eye"], "zh-CN": ["证誓之明瞳"] },
        materials: ["Coral Branch of a Distant Sea", "Concealed Claw", "Spectral Husk"],
    },
    {
        id: "Magic Guide",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CATALYST,
        name: { en: ["Magic Guide"], "zh-CN": ["魔导绪论"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Slime Condensate"],
    },
    {
        id: "Otherworldly Story",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CATALYST,
        name: { en: ["Otherworldly Story"], "zh-CN": ["异世界行记"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Damaged Mask"],
    },
    {
        id: "Emerald Orb",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CATALYST,
        name: { en: ["Emerald Orb"], "zh-CN": ["翡玉法球"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Treasure Hoarder Insignia"],
    },
    {
        id: "Thrilling Tales of Dragon Slayers",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CATALYST,
        name: { en: ["Thrilling Tales of Dragon Slayers"], "zh-CN": ["讨龙英杰谭"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Divining Scroll"],
    },
    {
        id: "Twin Nephrite",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CATALYST,
        name: { en: ["Twin Nephrite"], "zh-CN": ["甲级宝珏"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Recruit’s Insignia"],
    },
    {
        id: "Wolf’s Gravestone",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Wolf’s Gravestone"], "zh-CN": ["狼的末路"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Divining Scroll"],
    },
    {
        id: "Skyward Pride",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Skyward Pride"], "zh-CN": ["天空之傲"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Slime Condensate"],
    },
    {
        id: "The Unforged",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["The Unforged"], "zh-CN": ["无工之剑"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Treasure Hoarder Insignia"],
    },
    {
        id: "Song of Broken Pines",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Song of Broken Pines"], "zh-CN": ["松籁响起之时"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Damaged Mask"],
    },
    {
        id: "Redhorn Stonethresher",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Redhorn Stonethresher"], "zh-CN": ["赤角石溃杵"] },
        materials: ["Narukami’s Wisdom", "Concealed Claw", "Old Handguard"],
    },
    {
        id: "Akuoumaru",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Akuoumaru"], "zh-CN": ["恶王丸"] },
        materials: ["Coral Branch of a Distant Sea", "Concealed Claw", "Old Handguard"],
    },
    {
        id: "Royal Greatsword",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Royal Greatsword"], "zh-CN": ["宗室大剑"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Slime Condensate"],
    },
    {
        id: "Whiteblind",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Whiteblind"], "zh-CN": ["白影剑"] },
        materials: [
            "Northlander Claymore Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Luminous Sands from Guyun",
            "Hunter’s Sacrificial Knife",
            "Treasure Hoarder Insignia",
        ],
    },
    {
        id: "The Bell",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["The Bell"], "zh-CN": ["钟剑"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Whopperflower Nectar"],
    },
    {
        id: "Snow-Tombed Starsilver",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Snow-Tombed Starsilver"], "zh-CN": ["雪葬的星银"] },
        materials: [
            "Northlander Claymore Billet",
            "Crystal Chunk",
            "Starsilver",
            "Tile of Decarabian’s Tower",
            "Heavy Horn",
            "Slime Condensate",
        ],
    },
    {
        id: "Favonius Greatsword",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Favonius Greatsword"], "zh-CN": ["西风大剑"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Recruit’s Insignia"],
    },
    {
        id: "Katsuragikiri Nagamasa",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Katsuragikiri Nagamasa"], "zh-CN": ["桂木斩长正"] },
        materials: [
            "Northlander Claymore Billet",
            "Amethyst Lump",
            "White Iron Chunk",
            "Narukami’s Wisdom",
            "Chaos Gear",
            "Old Handguard",
        ],
    },
    {
        id: "Sacrificial Greatsword",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Sacrificial Greatsword"], "zh-CN": ["祭礼大剑"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Firm Arrowhead"],
    },
    {
        id: "Serpent Spine",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Serpent Spine"], "zh-CN": ["螭骨剑"] },
        materials: ["Grain of Aerosiderite", "Fragile Bone Shard", "Whopperflower Nectar"],
    },
    {
        id: "Blackcliff Slasher",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Blackcliff Slasher"], "zh-CN": ["黑岩斩刀"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Recruit’s Insignia"],
    },
    {
        id: "Rainslasher",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Rainslasher"], "zh-CN": ["雨裁"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Divining Scroll"],
    },
    {
        id: "Prototype Archaic",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Prototype Archaic"], "zh-CN": ["试作古华"] },
        materials: [
            "Northlander Claymore Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Grain of Aerosiderite",
            "Fragile Bone Shard",
            "Damaged Mask",
        ],
    },
    {
        id: "Luxurious Sea-Lord",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Luxurious Sea-Lord"], "zh-CN": ["衔珠海皇"] },
        materials: ["Grain of Aerosiderite", "Fragile Bone Shard", "Slime Condensate"],
    },
    {
        id: "Lithic Blade",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Lithic Blade"], "zh-CN": ["千岩古剑"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Firm Arrowhead"],
    },
    {
        id: "Skyrider Greatsword",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Skyrider Greatsword"], "zh-CN": ["飞天大御剑"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Damaged Mask"],
    },
    {
        id: "Debate Club",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Debate Club"], "zh-CN": ["以理服人"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Damaged Mask"],
    },
    {
        id: "Bloodtainted Greatsword",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Bloodtainted Greatsword"], "zh-CN": ["沐浴龙血的剑"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Firm Arrowhead"],
    },
    {
        id: "White Iron Greatsword",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["White Iron Greatsword"], "zh-CN": ["白铁大剑"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Slime Condensate"],
    },
    {
        id: "Ferrous Shadow",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.CLAYMORE,
        name: { en: ["Ferrous Shadow"], "zh-CN": ["铁影阔剑"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Whopperflower Nectar"],
    },
    {
        id: "Engulfing Lightning",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.POLEARM,
        name: { en: ["Engulfing Lightning"], "zh-CN": ["薙草之稻光"] },
        materials: ["Mask of the Wicked Lieutenant", "Chaos Gear", "Old Handguard"],
    },
    {
        id: "Skyward Spine",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.POLEARM,
        name: { en: ["Skyward Spine"], "zh-CN": ["天空之脊"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Divining Scroll"],
    },
    {
        id: "Primordial Jade Winged-Spear",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.POLEARM,
        name: { en: ["Primordial Jade Winged-Spear"], "zh-CN": ["和璞鸢"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Recruit’s Insignia"],
    },
    {
        id: "Calamity Queller",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.POLEARM,
        name: { en: ["Calamity Queller"], "zh-CN": ["息灾"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Whopperflower Nectar"],
    },
    {
        id: "Staff of Homa",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.POLEARM,
        name: { en: ["Staff of Homa"], "zh-CN": ["护摩之杖"] },
        materials: ["Grain of Aerosiderite", "Dead Ley Line Branch", "Slime Condensate"],
    },
    {
        id: "Vortex Vanquisher",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.POLEARM,
        name: { en: ["Vortex Vanquisher"], "zh-CN": ["贯虹之槊"] },
        materials: ["Grain of Aerosiderite", "Fragile Bone Shard", "Treasure Hoarder Insignia"],
    },
    {
        id: "Prototype Starglitter",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Prototype Starglitter"], "zh-CN": ["试作星镰"] },
        materials: [
            "Northlander Polearm Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Grain of Aerosiderite",
            "Fragile Bone Shard",
            "Damaged Mask",
        ],
    },
    {
        id: "Lithic Spear",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Lithic Spear"], "zh-CN": ["千岩长枪"] },
        materials: ["Grain of Aerosiderite", "Fragile Bone Shard", "Firm Arrowhead"],
    },
    {
        id: "Kitain Cross Spear",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Kitain Cross Spear"], "zh-CN": ["喜多院十文字"] },
        materials: [
            "Northlander Polearm Billet",
            "Amethyst Lump",
            "White Iron Chunk",
            "Mask of the Wicked Lieutenant",
            "Chaos Gear",
            "Treasure Hoarder Insignia",
        ],
    },
    {
        id: "“The Catch”",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["“The Catch”"], "zh-CN": ["「渔获」"] },
        materials: [
            "Mask of the Wicked Lieutenant",
            "Chaos Gear",
            "Spectral Husk",
            "Raimei Angelfish",
            "Golden Koi",
            "Rusty Koi",
            "Pufferfish",
            "Bitter Pufferfish",
        ],
    },
    {
        id: "Favonius Lance",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Favonius Lance"], "zh-CN": ["西风长枪"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Slime Condensate"],
    },
    {
        id: "Dragonspine Spear",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Dragonspine Spear"], "zh-CN": ["龙脊长枪"] },
        materials: [
            "Northlander Polearm Billet",
            "Starsilver",
            "Vitalized Dragontooth",
            "Boreal Wolf’s Milk Tooth",
            "Mist Grass Pollen",
            "Recruit’s Insignia",
        ],
    },
    {
        id: "Dragon’s Bane",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Dragon’s Bane"], "zh-CN": ["匣里灭辰"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Divining Scroll"],
    },
    {
        id: "Deathmatch",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Deathmatch"], "zh-CN": ["决斗之枪"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Whopperflower Nectar"],
    },
    {
        id: "Crescent Pike",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Crescent Pike"], "zh-CN": ["流月针"] },
        materials: [
            "Northlander Polearm Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Luminous Sands from Guyun",
            "Hunter’s Sacrificial Knife",
            "Treasure Hoarder Insignia",
        ],
    },
    {
        id: "Blackcliff Pole",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Blackcliff Pole"], "zh-CN": ["黑岩刺枪"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Recruit’s Insignia"],
    },
    {
        id: "Wavebreaker’s Fin",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Wavebreaker’s Fin"], "zh-CN": ["断浪长鳍"] },
        materials: ["Mask of the Wicked Lieutenant", "Concealed Claw", "Old Handguard"],
    },
    {
        id: "Royal Spear",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.POLEARM,
        name: { en: ["Royal Spear"], "zh-CN": ["宗室猎枪"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Recruit’s Insignia"],
    },
    {
        id: "Halberd",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.POLEARM,
        name: { en: ["Halberd"], "zh-CN": ["钺矛"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Whopperflower Nectar"],
    },
    {
        id: "Black Tassel",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.POLEARM,
        name: { en: ["Black Tassel"], "zh-CN": ["黑缨枪"] },
        materials: ["Grain of Aerosiderite", "Fragile Bone Shard", "Firm Arrowhead"],
    },
    {
        id: "White Tassel",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.POLEARM,
        name: { en: ["White Tassel"], "zh-CN": ["白缨枪"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Recruit’s Insignia"],
    },
    {
        id: "Mistsplitter Reforged",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.SWORD,
        name: { en: ["Mistsplitter Reforged"], "zh-CN": ["雾切之回光"] },
        materials: ["Coral Branch of a Distant Sea", "Chaos Gear", "Old Handguard"],
    },
    {
        id: "Aquila Favonia",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.SWORD,
        name: { en: ["Aquila Favonia"], "zh-CN": ["风鹰剑"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Firm Arrowhead"],
    },
    {
        id: "Summit Shaper",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.SWORD,
        name: { en: ["Summit Shaper"], "zh-CN": ["斫峰之刃"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Damaged Mask"],
    },
    {
        id: "Skyward Blade",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.SWORD,
        name: { en: ["Skyward Blade"], "zh-CN": ["天空之刃"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Slime Condensate"],
    },
    {
        id: "Freedom-Sworn",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.SWORD,
        name: { en: ["Freedom-Sworn"], "zh-CN": ["苍古自由之誓"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Divining Scroll"],
    },
    {
        id: "Primordial Jade Cutter",
        type: "weapon",
        rarity: 5,
        category: WeaponCategory.SWORD,
        name: { en: ["Primordial Jade Cutter"], "zh-CN": ["磐岩结绿"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Treasure Hoarder Insignia"],
    },
    {
        id: "The Flute",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["The Flute"], "zh-CN": ["笛剑"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Slime Condensate"],
    },
    {
        id: "The Black Sword",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["The Black Sword"], "zh-CN": ["黑剑"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Slime Condensate"],
    },
    {
        id: "The Alley Flash",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["The Alley Flash"], "zh-CN": ["暗巷闪光"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Divining Scroll"],
    },
    {
        id: "Sword of Descension",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Sword of Descension"], "zh-CN": ["降临之剑"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Treasure Hoarder Insignia"],
    },
    {
        id: "Sacrificial Sword",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Sacrificial Sword"], "zh-CN": ["祭礼剑"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Divining Scroll"],
    },
    {
        id: "Royal Longsword",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Royal Longsword"], "zh-CN": ["宗室长剑"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Damaged Mask"],
    },
    {
        id: "Prototype Rancour",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Prototype Rancour"], "zh-CN": ["试作斩岩"] },
        materials: [
            "Northlander Sword Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Mist Veiled Lead Elixir",
            "Mist Grass Pollen",
            "Recruit’s Insignia",
        ],
    },
    {
        id: "Amenoma Kageuchi",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Amenoma Kageuchi"], "zh-CN": ["天目影打刀"] },
        materials: [
            "Northlander Sword Billet",
            "Amethyst Lump",
            "White Iron Chunk",
            "Coral Branch of a Distant Sea",
            "Chaos Gear",
            "Old Handguard",
        ],
    },
    {
        id: "Lion’s Roar",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Lion’s Roar"], "zh-CN": ["匣里龙吟"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Treasure Hoarder Insignia"],
    },
    {
        id: "Iron Sting",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Iron Sting"], "zh-CN": ["铁蜂刺"] },
        materials: [
            "Northlander Sword Billet",
            "Crystal Chunk",
            "White Iron Chunk",
            "Grain of Aerosiderite",
            "Fragile Bone Shard",
            "Whopperflower Nectar",
        ],
    },
    {
        id: "Festering Desire",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Festering Desire"], "zh-CN": ["腐殖之剑"] },
        materials: ["Fetters of the Dandelion Gladiator", "Heavy Horn", "Recruit’s Insignia"],
    },
    {
        id: "Favonius Sword",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Favonius Sword"], "zh-CN": ["西风剑"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Firm Arrowhead"],
    },
    {
        id: "Cinnabar Spindle",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Cinnabar Spindle"], "zh-CN": ["辰砂之纺锤"] },
        materials: ["Tile of Decarabian’s Tower", "Chaos Device", "Damaged Mask"],
    },
    {
        id: "Blackcliff Longsword",
        type: "weapon",
        rarity: 4,
        category: WeaponCategory.SWORD,
        name: { en: ["Blackcliff Longsword"], "zh-CN": ["黑岩长剑"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Firm Arrowhead"],
    },
    {
        id: "Harbinger of Dawn",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.SWORD,
        name: { en: ["Harbinger of Dawn"], "zh-CN": ["黎明神剑"] },
        materials: ["Boreal Wolf’s Milk Tooth", "Dead Ley Line Branch", "Slime Condensate"],
    },
    {
        id: "Fillet Blade",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.SWORD,
        name: { en: ["Fillet Blade"], "zh-CN": ["吃虎鱼刀"] },
        materials: ["Mist Veiled Lead Elixir", "Mist Grass Pollen", "Treasure Hoarder Insignia"],
    },
    {
        id: "Skyrider Sword",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.SWORD,
        name: { en: ["Skyrider Sword"], "zh-CN": ["飞天御剑"] },
        materials: ["Grain of Aerosiderite", "Fragile Bone Shard", "Recruit’s Insignia"],
    },
    {
        id: "Dark Iron Sword",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.SWORD,
        name: { en: ["Dark Iron Sword"], "zh-CN": ["暗铁剑"] },
        materials: ["Luminous Sands from Guyun", "Hunter’s Sacrificial Knife", "Damaged Mask"],
    },
    {
        id: "Cool Steel",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.SWORD,
        name: { en: ["Cool Steel"], "zh-CN": ["冷刃"] },
        materials: ["Tile of Decarabian’s Tower", "Heavy Horn", "Firm Arrowhead"],
    },
    {
        id: "Traveler’s Handy Sword",
        type: "weapon",
        rarity: 3,
        category: WeaponCategory.SWORD,
        name: { en: ["Traveler’s Handy Sword"], "zh-CN": ["旅行剑"] },
        materials: ["Fetters of the Dandelion Gladiator", "Chaos Device", "Divining Scroll"],
    },
]; // materials
export const materials = [
    // common
    {
        id: "Slime Condensate",
        name: {
            en: ["Slime Condensate", "Slime Secretions", "Slime Concentrate"],
            "zh-CN": ["史莱姆凝液", "史莱姆清", "史莱姆原浆"],
        },
    },
    {
        id: "Damaged Mask",
        name: {
            en: ["Damaged Mask", "Stained Mask", "Ominous Mask"],
            "zh-CN": ["破损的面具", "污秽的面具", "不祥的面具"],
        },
    },
    {
        id: "Divining Scroll",
        name: {
            en: ["Divining Scroll", "Sealed Scroll", "Forbidden Curse Scroll"],
            "zh-CN": ["导能绘卷", "封魔绘卷", "禁咒绘卷"],
        },
    },
    {
        id: "Firm Arrowhead",
        name: {
            en: ["Firm Arrowhead", "Sharp Arrowhead", "Weathered Arrowhead"],
            "zh-CN": ["牢固的箭簇", "锐利的箭簇", "历战的箭簇"],
        },
    },
    {
        id: "Heavy Horn",
        name: {
            en: ["Heavy Horn", "Black Bronze Horn", "Black Crystal Horn"],
            "zh-CN": ["沉重号角", "黑铜号角", "黑晶号角"],
        },
    },
    {
        id: "Dead Ley Line Branch",
        name: {
            en: ["Dead Ley Line Branch", "Dead Ley Line Leaves", "Ley Line Sprout"],
            "zh-CN": ["地脉的旧枝", "地脉的枯叶", "地脉的新芽"],
        },
    },
    {
        id: "Chaos Device",
        name: { en: ["Chaos Device", "Chaos Circuit", "Chaos Core"], "zh-CN": ["混沌装置", "混沌回路", "混沌炉心"] },
    },
    {
        id: "Mist Grass Pollen",
        name: {
            en: ["Mist Grass Pollen", "Mist Grass", "Mist Grass Wick"],
            "zh-CN": ["雾虚花粉", "雾虚草囊", "雾虚灯芯"],
        },
    },
    {
        id: "Hunter’s Sacrificial Knife",
        name: {
            en: ["Hunter’s Sacrificial Knife", "Agent’s Sacrificial Knife", "Inspector’s Sacrificial Knife"],
            "zh-CN": ["猎兵祭刀", "特工祭刀", "督察长祭刀"],
        },
    },
    {
        id: "Recruit’s Insignia",
        name: {
            en: ["Recruit’s Insignia", "Sergeant’s Insignia", "Lieutenant’s Insignia"],
            "zh-CN": ["新兵的徽记", "士官的徽记", "尉官的徽记"],
        },
    },
    {
        id: "Treasure Hoarder Insignia",
        name: {
            en: ["Treasure Hoarder Insignia", "Silver Raven Insignia", "Golden Raven Insignia"],
            "zh-CN": ["寻宝鸦印", "藏银鸦印", "攫金鸦印"],
        },
    },
    {
        id: "Whopperflower Nectar",
        name: {
            en: ["Whopperflower Nectar", "Shimmering Nectar", "Energy Nectar"],
            "zh-CN": ["骗骗花蜜", "微光花蜜", "原素花蜜"],
        },
    },
    {
        id: "Fragile Bone Shard",
        name: {
            en: ["Fragile Bone Shard", "Sturdy Bone Shard", "Fossilized Bone Shard"],
            "zh-CN": ["脆弱的骨片", "结实的骨片", "石化的骨片"],
        },
    },
    {
        id: "Old Handguard",
        name: {
            en: ["Old Handguard", "Kageuchi Handguard", "Famed Handguard"],
            "zh-CN": ["破旧的刀镡", "影打刀镡", "名刀镡"],
        },
    },
    {
        id: "Chaos Gear",
        name: { en: ["Chaos Gear", "Chaos Axis", "Chaos Oculus"], "zh-CN": ["混沌机关", "混沌枢纽", "混沌真眼"] },
    },
    {
        id: "Dismal Prism",
        name: {
            en: ["Dismal Prism", "Crystal Prism", "Polarizing Prism"],
            "zh-CN": ["黯淡棱镜", "水晶棱镜", "偏光棱镜"],
        },
    },
    {
        id: "Spectral Husk",
        name: {
            en: ["Spectral Husk", "Spectral Heart", "Spectral Nucleus"],
            "zh-CN": ["浮游干核", "浮游幽核", "浮游晶化核"],
        },
    },
    {
        id: "Concealed Claw",
        name: {
            en: ["Concealed Claw", "Concealed Unguis", "Concealed Talon"],
            "zh-CN": ["隐兽指爪", "隐兽利爪", "隐兽鬼爪"],
        },
    },
    // local specialities
    { id: "Calla Lily", name: { en: ["Calla Lily"], "zh-CN": ["嘟嘟莲"] } },
    { id: "Cecilia", name: { en: ["Cecilia"], "zh-CN": ["塞西莉亚花"] } },
    { id: "Dandelion Seed", name: { en: ["Dandelion Seed"], "zh-CN": ["蒲公英籽"] } },
    { id: "Philanemo Mushroom", name: { en: ["Philanemo Mushroom"], "zh-CN": ["慕风蘑菇"] } },
    { id: "Small Lamp Grass", name: { en: ["Small Lamp Grass"], "zh-CN": ["小灯草"] } },
    { id: "Valberry", name: { en: ["Valberry"], "zh-CN": ["落落莓"] } },
    { id: "Windwheel Aster", name: { en: ["Windwheel Aster"], "zh-CN": ["风车菊"] } },
    { id: "Wolfhook", name: { en: ["Wolfhook"], "zh-CN": ["钩钩果"] } },
    { id: "Cor Lapis", name: { en: ["Cor Lapis"], "zh-CN": ["石珀"] } },
    { id: "Glaze Lily", name: { en: ["Glaze Lily"], "zh-CN": ["琉璃百合"] } },
    { id: "Jueyun Chili", name: { en: ["Jueyun Chili"], "zh-CN": ["绝云椒椒"] } },
    { id: "Noctilucous Jade", name: { en: ["Noctilucous Jade"], "zh-CN": ["夜泊石"] } },
    { id: "Qingxin", name: { en: ["Qingxin"], "zh-CN": ["清心"] } },
    { id: "Silk Flower", name: { en: ["Silk Flower"], "zh-CN": ["霓裳花"] } },
    { id: "Starconch", name: { en: ["Starconch"], "zh-CN": ["星螺"] } },
    { id: "Violetgrass", name: { en: ["Violetgrass"], "zh-CN": ["琉璃袋"] } },
    { id: "Amakumo Fruit", name: { en: ["Amakumo Fruit"], "zh-CN": ["天云草实"] } },
    { id: "Crystal Marrow", name: { en: ["Crystal Marrow"], "zh-CN": ["晶化骨髓"] } },
    { id: "Dendrobium", name: { en: ["Dendrobium"], "zh-CN": ["血斛"] } },
    { id: "Fluorescent Fungus", name: { en: ["Fluorescent Fungus"], "zh-CN": ["幽灯蕈"] } },
    { id: "Naku Weed", name: { en: ["Naku Weed"], "zh-CN": ["鸣草"] } },
    { id: "Onikabuto", name: { en: ["Onikabuto"], "zh-CN": ["鬼兜虫"] } },
    { id: "Sakura Bloom", name: { en: ["Sakura Bloom"], "zh-CN": ["绯樱绣球"] } },
    { id: "Sango Pearl", name: { en: ["Sango Pearl"], "zh-CN": ["珊瑚真珠"] } },
    { id: "Sea Ganoderma", name: { en: ["Sea Ganoderma"], "zh-CN": ["海灵芝"] } },
    // character ascension
    { id: "Brilliant Diamond", name: { en: ["Brilliant Diamond"], "zh-CN": ["璀璨原钻"] } },
    { id: "Agnidus Agate", name: { en: ["Agnidus Agate"], "zh-CN": ["燃愿玛瑙"] } },
    { id: "Varunada Lazurite", name: { en: ["Varunada Lazurite"], "zh-CN": ["涤净青金"] } },
    { id: "Vajrada Amethyst", name: { en: ["Vajrada Amethyst"], "zh-CN": ["最胜紫晶"] } },
    { id: "Vayuda Turquoise", name: { en: ["Vayuda Turquoise"], "zh-CN": ["自在松石"] } },
    { id: "Shivada Jade", name: { en: ["Shivada Jade"], "zh-CN": ["哀叙冰玉"] } },
    { id: "Prithiva Topaz", name: { en: ["Prithiva Topaz"], "zh-CN": ["坚牢黄玉"] } },
    { id: "Hurricane Seed", name: { en: ["Hurricane Seed"], "zh-CN": ["飓风之种"] } },
    { id: "Lightning Prism", name: { en: ["Lightning Prism"], "zh-CN": ["雷光棱镜"] } },
    { id: "Basalt Pillar", name: { en: ["Basalt Pillar"], "zh-CN": ["玄岩之塔"] } },
    { id: "Hoarfrost Core", name: { en: ["Hoarfrost Core"], "zh-CN": ["极寒之核"] } },
    { id: "Everflame Seed", name: { en: ["Everflame Seed"], "zh-CN": ["常燃火种"] } },
    { id: "Cleansing Heart", name: { en: ["Cleansing Heart"], "zh-CN": ["净水之心"] } },
    { id: "Juvenile Jade", name: { en: ["Juvenile Jade"], "zh-CN": ["未熟之玉"] } },
    { id: "Crystalline Bloom", name: { en: ["Crystalline Bloom"], "zh-CN": ["晶凝之华"] } },
    { id: "Marionette Core", name: { en: ["Marionette Core"], "zh-CN": ["魔偶机心"] } },
    { id: "Perpetual Heart", name: { en: ["Perpetual Heart"], "zh-CN": ["恒常机关之心"] } },
    { id: "Smoldering Pearl", name: { en: ["Smoldering Pearl"], "zh-CN": ["阴燃之珠"] } },
    { id: "Dew of Repudiation", name: { en: ["Dew of Repudiation"], "zh-CN": ["排异之露"] } },
    { id: "Storm Beads", name: { en: ["Storm Beads"], "zh-CN": ["雷霆数珠"] } },
    { id: "Riftborn Regalia", name: { en: ["Riftborn Regalia"], "zh-CN": ["兽境王器"] } },
    { id: "Dragonheir’s False Fin", name: { en: ["Dragonheir’s False Fin"], "zh-CN": ["龙嗣伪鳍"] } },
    // character talents
    { id: "Freedom", name: { en: ["Freedom"], "zh-CN": ["自由"] } },
    { id: "Resistance", name: { en: ["Resistance"], "zh-CN": ["抗争"] } },
    { id: "Ballad", name: { en: ["Ballad"], "zh-CN": ["诗文"] } },
    { id: "Prosperity", name: { en: ["Prosperity"], "zh-CN": ["繁荣"] } },
    { id: "Diligence", name: { en: ["Diligence"], "zh-CN": ["勤劳"] } },
    { id: "Gold", name: { en: ["Gold"], "zh-CN": ["黄金"] } },
    { id: "Transience", name: { en: ["Transience"], "zh-CN": ["浮世"] } },
    { id: "Elegance", name: { en: ["Elegance"], "zh-CN": ["风雅"] } },
    { id: "Light", name: { en: ["Light"], "zh-CN": ["天光"] } },
    { id: "Crown of Insight", name: { en: ["Crown of Insight"], "zh-CN": ["智识之冕"] } },
    { id: "Dvalin’s Plume", name: { en: ["Dvalin’s Plume"], "zh-CN": ["东风之翎"] } },
    { id: "Dvalin’s Claw", name: { en: ["Dvalin’s Claw"], "zh-CN": ["东风之爪"] } },
    { id: "Dvalin’s Sigh", name: { en: ["Dvalin’s Sigh"], "zh-CN": ["东风的吐息"] } },
    { id: "Tail of Boreas", name: { en: ["Tail of Boreas"], "zh-CN": ["北风之尾"] } },
    { id: "Ring of Boreas", name: { en: ["Ring of Boreas"], "zh-CN": ["北风之环"] } },
    { id: "Spirit Locket of Boreas", name: { en: ["Spirit Locket of Boreas"], "zh-CN": ["北风的魂匣"] } },
    { id: "Tusk of Monoceros Caeli", name: { en: ["Tusk of Monoceros Caeli"], "zh-CN": ["吞天之鲸・只角"] } },
    { id: "Shard of a Foul Legacy", name: { en: ["Shard of a Foul Legacy"], "zh-CN": ["魔王之刃・残片"] } },
    { id: "Shadow of the Warrior", name: { en: ["Shadow of the Warrior"], "zh-CN": ["武炼之魂・孤影"] } },
    { id: "Dragon Lord’s Crown", name: { en: ["Dragon Lord’s Crown"], "zh-CN": ["龙王之冕"] } },
    { id: "Bloodjade Branch", name: { en: ["Bloodjade Branch"], "zh-CN": ["血玉之枝"] } },
    { id: "Gilded Scale", name: { en: ["Gilded Scale"], "zh-CN": ["鎏金之鳞"] } },
    { id: "Molten Moment", name: { en: ["Molten Moment"], "zh-CN": ["熔毁之刻"] } },
    { id: "Hellfire Butterfly", name: { en: ["Hellfire Butterfly"], "zh-CN": ["狱火之蝶"] } },
    { id: "Ashen Heart", name: { en: ["Ashen Heart"], "zh-CN": ["灰烬之心"] } },
    // weapons
    {
        id: "Tile of Decarabian’s Tower",
        name: {
            en: [
                "Tile of Decarabian’s Tower",
                "Debris of Decarabian’s City",
                "Fragment of Decarabian’s Epic",
                "Scattered Piece of Decarabian’s Dream",
            ],
            "zh-CN": ["高塔孤王的破瓦", "高塔孤王的残垣", "高塔孤王的断片", "高塔孤王的碎梦"],
        },
    },
    {
        id: "Boreal Wolf’s Milk Tooth",
        name: {
            en: [
                "Boreal Wolf’s Milk Tooth",
                "Boreal Wolf’s Cracked Tooth",
                "Boreal Wolf’s Broken Fang",
                "Boreal Wolf’s Nostalgia",
            ],
            "zh-CN": ["凛风奔狼的始龀", "凛风奔狼的裂齿", "凛风奔狼的断牙", "凛风奔狼的怀乡"],
        },
    },
    {
        id: "Fetters of the Dandelion Gladiator",
        name: {
            en: [
                "Fetters of the Dandelion Gladiator",
                "Chains of the Dandelion Gladiator",
                "Shackles of the Dandelion Gladiator",
                "Dream of the Dandelion Gladiator",
            ],
            "zh-CN": ["狮牙斗士的枷锁", "狮牙斗士的铁链", "狮牙斗士的镣铐", "狮牙斗士的理想"],
        },
    },
    {
        id: "Luminous Sands from Guyun",
        name: {
            en: ["Luminous Sands from Guyun", "Lustrous Stone from Guyun", "Relic from Guyun", "Divine Body from Guyun"],
            "zh-CN": ["孤云寒林的光砂", "孤云寒林的辉岩", "孤云寒林的圣骸", "孤云寒林的神体"],
        },
    },
    {
        id: "Mist Veiled Lead Elixir",
        name: {
            en: [
                "Mist Veiled Lead Elixir",
                "Mist Veiled Mercury Elixir",
                "Mist Veiled Gold Elixir",
                "Mist Veiled Primo Elixir",
            ],
            "zh-CN": ["雾海云间的铅丹", "雾海云间的汞丹", "雾海云间的金丹", "雾海云间的转还"],
        },
    },
    {
        id: "Grain of Aerosiderite",
        name: {
            en: ["Grain of Aerosiderite", "Piece of Aerosiderite", "Bit of Aerosiderite", "Chunk of Aerosiderite"],
            "zh-CN": ["漆黑陨铁的一粒", "漆黑陨铁的一片", "漆黑陨铁的一角", "漆黑陨铁的一块"],
        },
    },
    {
        id: "Coral Branch of a Distant Sea",
        name: {
            en: [
                "Coral Branch of a Distant Sea",
                "Jeweled Branch of a Distant Sea",
                "Jade Branch of a Distant Sea",
                "Golden Branch of a Distant Sea",
            ],
            "zh-CN": ["远海夷地的瑚枝", "远海夷地的玉枝", "远海夷地的琼枝", "远海夷地的金枝"],
        },
    },
    {
        id: "Narukami’s Wisdom",
        name: {
            en: ["Narukami’s Wisdom", "Narukami’s Joy", "Narukami’s Affection", "Narukami’s Valor"],
            "zh-CN": ["鸣神御灵的明惠", "鸣神御灵的欢喜", "鸣神御灵的亲爱", "鸣神御灵的勇武"],
        },
    },
    {
        id: "Mask of the Wicked Lieutenant",
        name: {
            en: ["Mask of the Wicked Lieutenant", "Mask of the Tiger’s Bite", "Mask of the One-Horned", "Mask of the Kijin"],
            "zh-CN": ["今昔剧画之恶尉", "今昔剧画之虎啮", "今昔剧画之一角", "今昔剧画之鬼人"],
        },
    },
    // weapon forge
    { id: "Northlander Claymore Billet", name: { en: ["Northlander Claymore Billet"], "zh-CN": ["北陆双手剑原胚"] } },
    { id: "Northlander Polearm Billet", name: { en: ["Northlander Polearm Billet"], "zh-CN": ["北陆长柄武器原胚"] } },
    { id: "Northlander Sword Billet", name: { en: ["Northlander Sword Billet"], "zh-CN": ["北陆单手剑原胚"] } },
    { id: "Northlander Bow Billet", name: { en: ["Northlander Bow Billet"], "zh-CN": ["北陆弓原胚"] } },
    { id: "Northlander Catalyst Billet", name: { en: ["Northlander Catalyst Billet"], "zh-CN": ["北陆法器原胚"] } },
    { id: "Crystal Chunk", name: { en: ["Crystal Chunk"], "zh-CN": ["水晶块"] } },
    { id: "White Iron Chunk", name: { en: ["White Iron Chunk"], "zh-CN": ["白铁块"] } },
    { id: "Starsilver", name: { en: ["Starsilver"], "zh-CN": ["星银矿石"] } },
    { id: "Vitalized Dragontooth", name: { en: ["Vitalized Dragontooth"], "zh-CN": ["汲取了生命力的龙牙"] } },
    { id: "Amethyst Lump", name: { en: ["Amethyst Lump"], "zh-CN": ["紫晶块"] } },
    // fishing
    { id: "Raimei Angelfish", name: { en: ["Raimei Angelfish"], "zh-CN": ["雷鸣仙"] } },
    { id: "Golden Koi", name: { en: ["Golden Koi"], "zh-CN": ["金赤假龙"] } },
    { id: "Rusty Koi", name: { en: ["Rusty Koi"], "zh-CN": ["锖假龙"] } },
    { id: "Pufferfish", name: { en: ["Pufferfish"], "zh-CN": ["炮鲀"] } },
    { id: "Bitter Pufferfish", name: { en: ["Bitter Pufferfish"], "zh-CN": ["苦炮鲀"] } },
];
// enemies
export const enemy_ids = new Map(Object.entries({
    weekly_bosses: [
        "Confront Stormterror",
        "Enter the Golden House",
        "Narukami Island: Tenshukaku",
        "Beneath the Dragon-Queller",
        "Wolf of the North Challenge",
    ],
    bosses: [
        "Electro Hypostasis",
        "Anemo Hypostasis",
        "Cryo Regisvine",
        "Geo Hypostasis",
        "Rhodeia of Loch",
        "Pyro Regisvine",
        "Primo Geovishap",
        "Cryo Hypostasis",
        "Maguu Kenki",
        "Pyro Hypostasis",
        "Perpetual Mechanical Array",
        "Hydro Hypostasis",
        "Thunder Manifestation",
        "Golden Wolflord",
        "Bathysmal Vishap Herd",
    ],
    talent_domains: ["Forsaken Rift", "Taishan Mansion", "Violet Court"],
    weapon_domains: ["Cecilia Garden", "Hidden Palace of Lianshan Formula", "Court of Flowing Sand"],
}));
export const domains = [
    {
        id: "Forsaken Rift",
        name: { en: ["Forsaken Rift"], "zh-CN": ["忘却之峡"] },
        type: "talent_domain",
        materials_by_weekday: ["All", "Freedom", "Resistance", "Ballad"],
    },
    {
        id: "Taishan Mansion",
        name: { en: ["Taishan Mansion"], "zh-CN": ["太山府"] },
        type: "talent_domain",
        materials_by_weekday: ["All", "Prosperity", "Diligence", "Gold"],
    },
    {
        id: "Violet Court",
        name: { en: ["Violet Court"], "zh-CN": ["菫色之庭"] },
        type: "talent_domain",
        materials_by_weekday: ["All", "Transience", "Elegance", "Light"],
    },
    {
        id: "Cecilia Garden",
        name: { en: ["Cecilia Garden"], "zh-CN": ["塞西莉亚苗圃"] },
        type: "weapon_domain",
        materials_by_weekday: [
            "All",
            "Tile of Decarabian’s Tower",
            "Boreal Wolf’s Milk Tooth",
            "Fetters of the Dandelion Gladiator",
        ],
    },
    {
        id: "Hidden Palace of Lianshan Formula",
        name: { en: ["Hidden Palace of Lianshan Formula"], "zh-CN": ["震雷连山密宫"] },
        type: "weapon_domain",
        materials_by_weekday: ["All", "Luminous Sands from Guyun", "Mist Veiled Lead Elixir", "Grain of Aerosiderite"],
    },
    {
        id: "Court of Flowing Sand",
        name: { en: ["Court of Flowing Sand"], "zh-CN": ["砂流之庭"] },
        type: "weapon_domain",
        materials_by_weekday: [
            "All",
            "Coral Branch of a Distant Sea",
            "Narukami’s Wisdom",
            "Mask of the Wicked Lieutenant",
        ],
    },
];
const billets = [
    "Northlander Claymore Billet",
    "Northlander Polearm Billet",
    "Northlander Sword Billet",
    "Northlander Bow Billet",
    "Northlander Catalyst Billet",
];
export const bosses = [
    {
        id: "Anemo Hypostasis",
        materials: ["Vayuda Turquoise", "Hurricane Seed"],
        type: "boss",
        name: { en: ["Anemo Hypostasis"], "zh-CN": ["无相之风"] },
    },
    {
        id: "Bathysmal Vishap Herd",
        materials: ["Shivada Jade", "Vajrada Amethyst", "Dragonheir’s False Fin"],
        type: "boss",
        name: { en: ["Bathysmal Vishap Herd"], "zh-CN": ["深海龙蜥"] },
    },
    {
        id: "Cryo Hypostasis",
        materials: ["Shivada Jade", "Crystalline Bloom"],
        type: "boss",
        name: { en: ["Cryo Hypostasis"], "zh-CN": ["无相之冰"] },
    },
    {
        id: "Cryo Regisvine",
        materials: ["Shivada Jade", "Hoarfrost Core"],
        type: "boss",
        name: { en: ["Cryo Regisvine"], "zh-CN": ["急冻树"] },
    },
    {
        id: "Electro Hypostasis",
        materials: ["Vajrada Amethyst", "Lightning Prism"],
        type: "boss",
        name: { en: ["Electro Hypostasis"], "zh-CN": ["无相之雷"] },
    },
    {
        id: "Geo Hypostasis",
        materials: ["Prithiva Topaz", "Basalt Pillar"],
        type: "boss",
        name: { en: ["Geo Hypostasis"], "zh-CN": ["无相之岩"] },
    },
    {
        id: "Golden Wolflord",
        materials: ["Prithiva Topaz", "Riftborn Regalia"],
        type: "boss",
        name: { en: ["Golden Wolflord"], "zh-CN": ["黄金王兽"] },
    },
    {
        id: "Hydro Hypostasis",
        materials: ["Varunada Lazurite", "Dew of Repudiation"],
        type: "boss",
        name: { en: ["Hydro Hypostasis"], "zh-CN": ["无相之水"] },
    },
    {
        id: "Maguu Kenki",
        materials: ["Vayuda Turquoise", "Shivada Jade", "Marionette Core"],
        type: "boss",
        name: { en: ["Maguu Kenki"], "zh-CN": ["魔偶剑鬼"] },
    },
    {
        id: "Perpetual Mechanical Array",
        materials: ["Prithiva Topaz", "Shivada Jade", "Perpetual Heart"],
        type: "boss",
        name: { en: ["Perpetual Mechanical Array"], "zh-CN": ["恒常机关阵列"] },
    },
    {
        id: "Primo Geovishap",
        materials: [
            "Prithiva Topaz",
            "Shivada Jade",
            "Agnidus Agate",
            "Varunada Lazurite",
            "Vajrada Amethyst",
            "Juvenile Jade",
        ],
        type: "boss",
        name: { en: ["Primo Geovishap"], "zh-CN": ["古岩龙蜥"] },
    },
    {
        id: "Pyro Hypostasis",
        materials: ["Agnidus Agate", "Smoldering Pearl"],
        type: "boss",
        name: { en: ["Pyro Hypostasis"], "zh-CN": ["无相之火"] },
    },
    {
        id: "Pyro Regisvine",
        materials: ["Agnidus Agate", "Everflame Seed"],
        type: "boss",
        name: { en: ["Pyro Regisvine"], "zh-CN": ["爆炎树"] },
    },
    {
        id: "Rhodeia of Loch",
        materials: ["Varunada Lazurite", "Cleansing Heart"],
        type: "boss",
        name: { en: ["Rhodeia of Loch"], "zh-CN": ["纯水精灵"] },
    },
    {
        id: "Thunder Manifestation",
        materials: ["Vajrada Amethyst", "Storm Beads"],
        type: "boss",
        name: { en: ["Thunder Manifestation"], "zh-CN": ["雷音权现"] },
    },
    // weekly bosses
    {
        id: "Wolf of the North Challenge",
        materials: [
            "Shivada Jade",
            "Agnidus Agate",
            "Prithiva Topaz",
            "Tail of Boreas",
            "Ring of Boreas",
            "Spirit Locket of Boreas",
            ...billets,
        ],
        type: "weekly_boss",
        name: { en: ["Wolf of the North Challenge / Andrius"], "zh-CN": ["北风的王狼 / 安德留斯"] },
    },
    {
        id: "Confront Stormterror",
        materials: [
            "Vayuda Turquoise",
            "Vajrada Amethyst",
            "Varunada Lazurite",
            "Dvalin’s Plume",
            "Dvalin’s Claw",
            "Dvalin’s Sigh",
            ...billets,
        ],
        type: "weekly_boss",
        name: { en: ["Confront Stormterror / Dvalin"], "zh-CN": ["深入风龙废墟 / 风魔龙・特瓦林"] },
    },
    {
        id: "Enter the Golden House",
        materials: [
            "Varunada Lazurite",
            "Vajrada Amethyst",
            "Shivada Jade",
            "Tusk of Monoceros Caeli",
            "Shard of a Foul Legacy",
            "Shadow of the Warrior",
            ...billets,
        ],
        type: "weekly_boss",
        name: { en: ["Enter the Golden House / Childe"], "zh-CN": ["进入「黄金屋」 / 公子"] },
    },
    {
        id: "Beneath the Dragon-Queller",
        materials: [
            "Agnidus Agate",
            "Shivada Jade",
            "Prithiva Topaz",
            "Varunada Lazurite",
            "Vajrada Amethyst",
            "Dragon Lord’s Crown",
            "Bloodjade Branch",
            "Gilded Scale",
            ...billets,
        ],
        type: "weekly_boss",
        name: { en: ["Beneath the Dragon-Queller / Azhdaha"], "zh-CN": ["「伏龙树」之底 / 若陀龙王"] },
    },
    {
        id: "Narukami Island: Tenshukaku",
        materials: ["Shivada Jade", "Agnidus Agate", "Molten Moment", "Hellfire Butterfly", "Ashen Heart", ...billets],
        type: "weekly_boss",
        name: { en: ["Narukami Island: Tenshukaku / La Signora"], "zh-CN": ["鸣神岛・天守 / 女士"] },
    },
];
export const i18n = {
    supportedLanguageSelectors: { en: ["English"], "zh-CN": ["简体中文"] },
    delimiter: { en: [" · "], "zh-CN": ["・"] },
    character: { en: ["Characters"], "zh-CN": ["角色"] },
    weapon: { en: ["Weapons"], "zh-CN": ["武器"] },
    enemies_domains: { en: ["Enemies & Domains"], "zh-CN": ["秘境讨伐"] },
    weekly_boss: { en: ["Weekly Bosses"], "zh-CN": ["周本"] },
    boss: { en: ["Bosses"], "zh-CN": ["首领"] },
    talent_domain: { en: ["Talent Domains"], "zh-CN": ["天赋本"] },
    weapon_domain: { en: ["Weapon Domains"], "zh-CN": ["武器本"] },
    today: { en: ["Today"], "zh-CN": ["今日"] },
};
/**
 * Index same as {@link Date.getDay}; [0] declared but not used.
 */
export const i18nWeekdays = [
    { en: ["Sun"], "zh-CN": ["日"] },
    { en: ["Mon, Thu, Sun"], "zh-CN": ["一四日"] },
    { en: ["Tue, Fri, Sun"], "zh-CN": ["二五日"] },
    { en: ["Wed, Sat, Sun"], "zh-CN": ["三六日"] },
];
