const domains = {
  "Cecilia Garden": {
    name: { en: "Cecilia Garden", zh_CN: "塞西莉亚苗圃" },
    materials_by_weekday: [
      "All",
      "Tile of Decarabian's Tower",
      "Boreal Wolf's Milk Tooth",
      "Fetters of the Dandelion Gladiator",
      "Tile of Decarabian's Tower",
      "Boreal Wolf's Milk Tooth",
      "Fetters of the Dandelion Gladiator",
    ],
  },
  "Hidden Palace of Lianshan Formula": {
    name: { en: "Hidden Palace of Lianshan Formula", zh_CN: "震雷连山密宫" },
    materials_by_weekday: [
      "All",
      "Luminous Sands from Guyun",
      "Mist Veiled Lead Elixir",
      "Grain of Aerosiderite",
      "Luminous Sands from Guyun",
      "Mist Veiled Lead Elixir",
      "Grain of Aerosiderite",
    ],
  },
  "Court of Flowing Sand": {
    name: { en: "Court of Flowing Sand", zh_CN: "砂流之庭" },
    materials_by_weekday: [
      "All",
      "Coral Branch of a Distant Sea",
      "Narukami's Wisdom",
      "Mask of the Wicked Lieutenant",
      "Coral Branch of a Distant Sea",
      "Narukami's Wisdom",
      "Mask of the Wicked Lieutenant",
    ],
  },
  "Forsaken Rift": {
    name: { en: "Forsaken Rift", zh_CN: "忘却之峡" },
    materials_by_weekday: ["All", "Freedom", "Resistance", "Ballad", "Freedom", "Resistance", "Ballad"],
  },
  "Taishan Mansion": {
    name: { en: "Taishan Mansion", zh_CN: "太山府" },
    materials_by_weekday: ["All", "Prosperity", "Diligence", "Gold", "Prosperity", "Diligence", "Gold"],
  },
  "Violet Court": {
    name: { en: "Violet Court", zh_CN: "菫色之庭" },
    materials_by_weekday: ["All", "Transience", "Elegance", "Light", "Transience", "Elegance", "Light"],
  },
};

const bosses = {
  "Anemo Hypostasis": {
    materials: ["Vayuda Turquoise", "Hurricane Seed"],
    name: { en: "Anemo Hypostasis", zh_CN: "无相之风" },
  },
  "Bathysmal Vishap Herd": {
    materials: ["Shivada Jade", "Vajrada Amethyst", "Dragonheir's False Fin"],
    name: { en: "Bathysmal Vishap Herd", zh_CN: "深海龙蜥" },
  },
  "Cryo Hypostasis": {
    materials: ["Shivada Jade", "Crystalline Bloom"],
    name: { en: "Cryo Hypostasis", zh_CN: "无相之冰" },
  },
  "Cryo Regisvine": {
    materials: ["Shivada Jade", "Hoarfrost Core"],
    name: { en: "Cryo Regisvine", zh_CN: "急冻树" },
  },
  "Electro Hypostasis": {
    materials: ["Vajrada Amethyst", "Lightning Prism"],
    name: { en: "Electro Hypostasis", zh_CN: "无相之雷" },
  },
  "Geo Hypostasis": {
    materials: ["Prithiva Topaz", "Basalt Pillar"],
    name: { en: "Geo Hypostasis", zh_CN: "无相之岩" },
  },
  "Golden Wolflord": {
    materials: ["Prithiva Topaz", "Riftborn Regalia"],
    name: { en: "Golden Wolflord", zh_CN: "黄金王兽" },
  },
  "Hydro Hypostasis": {
    materials: ["Varunada Lazurite", "Dew of Repudiation"],
    name: { en: "Hydro Hypostasis", zh_CN: "无相之水" },
  },
  "Maguu Kenki": {
    materials: ["Vayuda Turquoise", "Shivada Jade", "Marionette Core"],
    name: { en: "Maguu Kenki", zh_CN: "魔偶剑鬼" },
  },
  "Perpetual Mechanical Array": {
    materials: ["Prithiva Topaz", "Shivada Jade", "Perpetual Heart"],
    name: { en: "Perpetual Mechanical Array", zh_CN: "恒常机关阵列" },
  },
  "Primo Geovishap": {
    materials: [
      "Prithiva Topaz",
      "Shivada Jade",
      "Agnidus Agate",
      "Varunada Lazurite",
      "Vajrada Amethyst",
      "Juvenile Jade",
    ],
    name: { en: "Primo Geovishap", zh_CN: "古岩龙蜥" },
  },
  "Pyro Hypostasis": {
    materials: ["Agnidus Agate", "Smoldering Pearl"],
    name: { en: "Pyro Hypostasis", zh_CN: "无相之火" },
  },
  "Pyro Regisvine": {
    materials: ["Agnidus Agate", "Everflame Seed"],
    name: { en: "Pyro Regisvine", zh_CN: "爆炎树" },
  },
  "Rhodeia of Loch": {
    materials: ["Varunada Lazurite", "Cleansing Heart"],
    name: { en: "Rhodeia of Loch", zh_CN: "纯水精灵" },
  },
  "Thunder Manifestation": {
    materials: ["Vajrada Amethyst", "Storm Beads"],
    name: { en: "Thunder Manifestation", zh_CN: "雷音权现" },
  },
};

const weekly_bosses = {
  "Wolf of the North Challenge": {
    materials: [
      "Shivada Jade",
      "Agnidus Agate",
      "Prithiva Topaz",
      "Tail of Boreas",
      "Ring of Boreas",
      "Spirit Locket of Boreas",
    ],
    name: { en: "Wolf of the North Challenge / Andrius", zh_CN: "北风的王狼 安德留斯" },
  },
  "Confront Stormterror": {
    materials: [
      "Vayuda Turquoise",
      "Vajrada Amethyst",
      "Varunada Lazurite",
      "Dvalin's Plume",
      "Dvalin's Claw",
      "Dvalin's Sigh",
    ],
    name: { en: "Confront Stormterror / Dvalin", zh_CN: "深入风龙废墟 风魔龙・特瓦林" },
  },
  "Enter the Golden House": {
    materials: [
      "Varunada Lazurite",
      "Vajrada Amethyst",
      "Shivada Jade",
      "Tusk of Monoceros Caeli",
      "Shard of a Foul Legacy",
      "Shadow of the Warrior",
    ],
    name: { en: "Enter the Golden House / Childe", zh_CN: "进入「黄金屋」 公子" },
  },
  "Beneath the Dragon-Queller": {
    materials: [
      "Agnidus Agate",
      "Shivada Jade",
      "Prithiva Topaz",
      "Varunada Lazurite",
      "Vajrada Amethyst",
      "Dragon Lord's Crown",
      "Bloodjade Branch",
      "Gilded Scale",
    ],
    name: { en: "Beneath the Dragon-Queller / Azhdaha", zh_CN: "「伏龙树」之底 若陀龙王" },
  },
  "Narukami Island: Tenshukaku": {
    materials: ["Shivada Jade", "Agnidus Agate", "Molten Moment", "Hellfire Butterfly", "Ashen Heart"],
    name: { en: "Narukami Island: Tenshukaku / La Signora", zh_CN: "鸣神岛・天守 女士" },
  },
};

const zh_to_en = {
  史莱姆凝液: "Slime Condensate",
  史莱姆清: "Slime Condensate",
  史莱姆原浆: "Slime Condensate",
  破损的面具: "Damaged Mask",
  污秽的面具: "Damaged Mask",
  不祥的面具: "Damaged Mask",
  导能绘卷: "Divining Scroll",
  封魔绘卷: "Divining Scroll",
  禁咒绘卷: "Divining Scroll",
  牢固的箭簇: "Firm Arrowhead",
  锐利的箭簇: "Firm Arrowhead",
  历战的箭簇: "Firm Arrowhead",
  沉重号角: "Heavy Horn",
  黑铜号角: "Heavy Horn",
  黑晶号角: "Heavy Horn",
  地脉的旧枝: "Dead Ley Line Branch",
  地脉的枯叶: "Dead Ley Line Branch",
  地脉的新芽: "Dead Ley Line Branch",
  混沌装置: "Chaos Device",
  混沌回路: "Chaos Device",
  混沌炉心: "Chaos Device",
  雾虚花粉: "Mist Grass Pollen",
  雾虚草囊: "Mist Grass Pollen",
  雾虚灯芯: "Mist Grass Pollen",
  猎兵祭刀: "Hunter's Sacrificial Knife",
  特工祭刀: "Hunter's Sacrificial Knife",
  督察长祭刀: "Hunter's Sacrificial Knife",
  新兵的徽记: "Recruit's Insignia",
  士官的徽记: "Recruit's Insignia",
  尉官的徽记: "Recruit's Insignia",
  寻宝鸦印: "Treasure Hoarder Insignia",
  藏银鸦印: "Treasure Hoarder Insignia",
  攫金鸦印: "Treasure Hoarder Insignia",
  骗骗花蜜: "Whopperflower Nectar",
  微光花蜜: "Whopperflower Nectar",
  原素花蜜: "Whopperflower Nectar",
  脆弱的骨片: "Fragile Bone Shard",
  结实的骨片: "Fragile Bone Shard",
  石化的骨片: "Fragile Bone Shard",
  破旧的刀镡: "Old Handguard",
  影打刀镡: "Old Handguard",
  名刀镡: "Old Handguard",
  混沌机关: "Chaos Gear",
  混沌枢纽: "Chaos Gear",
  混沌真眼: "Chaos Gear",
  黯淡棱镜: "Dismal Prism",
  水晶棱镜: "Dismal Prism",
  偏光棱镜: "Dismal Prism",
  浮游干核: "Spectral Husk",
  浮游幽核: "Spectral Husk",
  浮游晶化核: "Spectral Husk",
  隐兽指爪: "Concealed Claw",
  隐兽利爪: "Concealed Claw",
  隐兽鬼爪: "Concealed Claw",
  高塔孤王的破瓦: "Tile of Decarabian's Tower",
  高塔孤王的残垣: "Tile of Decarabian's Tower",
  高塔孤王的断片: "Tile of Decarabian's Tower",
  高塔孤王的碎梦: "Tile of Decarabian's Tower",
  凛风奔狼的始龀: "Boreal Wolf's Milk Tooth",
  凛风奔狼的裂齿: "Boreal Wolf's Milk Tooth",
  凛风奔狼的断牙: "Boreal Wolf's Milk Tooth",
  凛风奔狼的怀乡: "Boreal Wolf's Milk Tooth",
  狮牙斗士的枷锁: "Fetters of the Dandelion Gladiator",
  狮牙斗士的铁链: "Fetters of the Dandelion Gladiator",
  狮牙斗士的镣铐: "Fetters of the Dandelion Gladiator",
  狮牙斗士的理想: "Fetters of the Dandelion Gladiator",
  孤云寒林的光砂: "Luminous Sands from Guyun",
  孤云寒林的辉岩: "Luminous Sands from Guyun",
  孤云寒林的圣骸: "Luminous Sands from Guyun",
  孤云寒林的神体: "Luminous Sands from Guyun",
  雾海云间的铅丹: "Mist Veiled Lead Elixir",
  雾海云间的汞丹: "Mist Veiled Lead Elixir",
  雾海云间的金丹: "Mist Veiled Lead Elixir",
  雾海云间的转还: "Mist Veiled Lead Elixir",
  漆黑陨铁的一粒: "Grain of Aerosiderite",
  漆黑陨铁的一片: "Grain of Aerosiderite",
  漆黑陨铁的一角: "Grain of Aerosiderite",
  漆黑陨铁的一块: "Grain of Aerosiderite",
  远海夷地的瑚枝: "Coral Branch of a Distant Sea",
  远海夷地的玉枝: "Coral Branch of a Distant Sea",
  远海夷地的琼枝: "Coral Branch of a Distant Sea",
  远海夷地的金枝: "Coral Branch of a Distant Sea",
  鸣神御灵的明惠: "Narukami's Wisdom",
  鸣神御灵的欢喜: "Narukami's Wisdom",
  鸣神御灵的亲爱: "Narukami's Wisdom",
  鸣神御灵的勇武: "Narukami's Wisdom",
  今昔剧画之恶尉: "Mask of the Wicked Lieutenant",
  今昔剧画之虎啮: "Mask of the Wicked Lieutenant",
  今昔剧画之一角: "Mask of the Wicked Lieutenant",
  今昔剧画之鬼人: "Mask of the Wicked Lieutenant",
  璀璨原钻: "Brilliant Diamond",
  燃愿玛瑙: "Agnidus Agate",
  涤净青金: "Varunada Lazurite",
  最胜紫晶: "Vajrada Amethyst",
  自在松石: "Vayuda Turquoise",
  哀叙冰玉: "Shivada Jade",
  坚牢黄玉: "Prithiva Topaz",
  飓风之种: "Hurricane Seed",
  雷光棱镜: "Lightning Prism",
  玄岩之塔: "Basalt Pillar",
  极寒之核: "Hoarfrost Core",
  常燃火种: "Everflame Seed",
  净水之心: "Cleansing Heart",
  未熟之玉: "Juvenile Jade",
  晶凝之华: "Crystalline Bloom",
  魔偶机心: "Marionette Core",
  恒常机关之心: "Perpetual Heart",
  阴燃之珠: "Smoldering Pearl",
  排异之露: "Dew of Repudiation",
  雷霆数珠: "Storm Beads",
  兽境王器: "Riftborn Regalia",
  龙嗣伪鳍: "Dragonheir's False Fin",
  自由: "Freedom",
  抗争: "Resistance",
  诗文: "Ballad",
  繁荣: "Prosperity",
  勤劳: "Diligence",
  黄金: "Gold",
  浮世: "Transience",
  风雅: "Elegance",
  天光: "Light",
  智识之冕: "Crown of Insight",
  东风之翎: "Dvalin's Plume",
  东风之爪: "Dvalin's Claw",
  东风的吐息: "Dvalin's Sigh",
  北风之尾: "Tail of Boreas",
  北风之环: "Ring of Boreas",
  北风的魂匣: "Spirit Locket of Boreas",
  "吞天之鲸・只角": "Tusk of Monoceros Caeli",
  "魔王之刃・残片": "Shard of a Foul Legacy",
  "武炼之魂・孤影": "Shadow of the Warrior",
  龙王之冕: "Dragon Lord's Crown",
  血玉之枝: "Bloodjade Branch",
  鎏金之鳞: "Gilded Scale",
  熔毁之刻: "Molten Moment",
  狱火之蝶: "Hellfire Butterfly",
  灰烬之心: "Ashen Heart",
};

for (const [id, enemy] of Object.entries(enemies)) {
  const l = enemy.materials.length;
  enemy.materials.forEach((m) => {
    enemy.materials.push(zh_to_en[m]);
  });
  enemy.materials = enemy.materials.slice(l);
}

console.log(enemies);
